FROM clearlinux/tensorflow
RUN swupd clean
RUN swupd bundle-add strace
RUN swupd clean
RUN swupd bundle-add git
RUN git clone https://github.com/phoronix-test-suite/phoronix-test-suite.git
RUN cd phoronix-test-suite/ && ./install-sh
